services:
  nginx:
    build:
      context: .
      dockerfile: "docker/nginx.dockerfile"
    hostname: "nginx"
    ports : 
        - 81:81
        - 444:444

  postgis:
    image: postgis/postgis:latest
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=neo
    - POSTGRES_DB=geostyledb
    - POSTGRES_PASSWORD=excal1b3r321123

  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/app.dockerfile
  #   volumes:
  #     - .:/geostyleapi
  #   restart: unless-stopped
  #   depends_on:
  #     - postgis
  #   container_name: geostyleapi
  #   environment:
  #     - DB_PORT=${POSTGIS_PORT}
  #     - DB_HOST=${POSTGIS_HOST}

volumes:
  db_data:
